### ISSUE TITLE
Support 5.5

### ISSUE THREAD

**Issue by goyote** [LaravelCollective/html#412] opened 2017-08-31 10:28 UTC
Problem 1
    - Conclusion: remove laravel/framework v5.5.0
    - Conclusion: don't install laravel/framework v5.5.0

**Comment by teddywest32** [comment] 2017-08-31 11:08
Duplicate of: https://github.com/LaravelCollective/html/issues/410

**Comment by cmizzi** [comment] 2017-08-31 12:04
Please see #409, #410 and #411 :smiley:

**Comment by balping** [comment] 2017-08-31 14:40
It's been released !

**Closed** 2017-08-31 14:56 UTC

**Comment by robertnicjoo** [comment] 2017-09-01 10:38
@balpin where is that released that I can't find it?

**Comment by balping** [comment] 2017-09-01 10:39
@robertnicjoo 

https://github.com/LaravelCollective/html/releases

**Comment by robertnicjoo** [comment] 2017-09-01 10:42
@balping and any idea how to install it? :-D

**Comment by balping** [comment] 2017-09-01 10:43
composer require laravelcollective/html
