### ISSUE TITLE
Form input arrays not working.

### ISSUE THREAD

**Issue by nat-mystudiosessions** [LaravelCollective/html#348] opened 2017-05-26 18:21 UTC
I have an input array: `{{Form::hidden('position_ids[]', $position_id)}}`

When I submit, I get an error:
```
ErrorException in C:\laragon\www\mystudiosessions\vendor\laravel\framework\src\Illuminate\Support\helpers.php line 533:
htmlspecialchars() expects parameter 1 to be string, array given
```
When I change it to `<input type="hidden" name="position_ids[]" value="{{$position_id}}"/>` it works fine.

Any ideas?

**Comment by decadence** [comment] 2017-05-26 18:32
https://github.com/LaravelCollective/html/issues/122

**Comment by DarkCobalt** [comment] 2017-06-05 09:07
+1

**Comment by decadence** [comment] 2017-06-05 09:43
You should close it since it's duplicate of another issue which is resolved.

**Comment by DarkCobalt** [comment] 2017-06-05 09:48
This is not resolve my problem, because i want create array without static index. Actually i must return to previous version of package.

**Comment by nat-mystudiosessions** [comment] 2017-06-06 21:09
Thanks @decadence

**Closed** 2017-06-06 21:08 UTC
